pipeline {
    agent any

    tools {
        maven 'Maven-3.9.11'     // Configure this name in Jenkins → Global Tool Configuration
        jdk 'jdk17'           // Configure JDK name in Jenkins
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out project from GitHub...'
                checkout scm
            }
        }

        stage('Build') {
            steps {
               echo 'Running Maven build inside /second folder...'
                dir('second') {     // <-- IMPORTANT FIX
                    bat 'mvn clean install -DskipTests'
                    }
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully!'
             archiveArtifacts artifacts: 'second/target/**/*', fingerprint: true
        }
        failure {
            echo 'Build failed!'
        }
    }
}
